# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/
version: 1.0.{build}
#image: WMF 5
environment:
  ModuleName: Infoblox
  ResourceGroupName: infobloxtesting
  location: SouthCentralUS
  IBAdminPassword:
    secure: +Yhi3I1uR1xjocdrPn5HGA==
  AzurePassword:
    secure: YsJNS6K8bf+aQp94gs6CJA==
  AzureTenantID:
    secure: 9dde4IdsaFmMXI+c8qpfltOt1vXkebzQldt43KK3i8ips7SWYUw8M3Z0ueHZkJcx
  AzureAppLoginID:
    secure: eeRsMl/TAFnKPf6nqz/GlZ1PRdvIj/QhgSOqWDalQAQy5o+4OW8J5bWrZAp+rp7McQ6C/GAgkr6ypF0vTmA4ysAYsCcwqwBOzIxze2KQwaI=
  PSGalleryAPIKey:
    secure: xDwME6mHDFid5MFHB4Vi2HRYZo35I0a8fceT8LR8feHLhroh9jRJIOnvSyPnB89J
build: false
test_script:
 - ps: . .\appveyor.ps1
